### ISSUE TITLE
Automatically add line number in log messages?

### ISSUE THREAD

**Issue by aliakhtar** [typesafehub/scala-logging#100]
Hey,

Coming from `java.util.Logging.logger`, I'm used to having the line number + method automatically included above each log message.

Is there a way to replicate that in this library?

I know there's a lib which lets you get the source code file, which you can include in your own message manually, but i'd like to just log the message and have the line number / file just added by default.

May be some sort of implicit magic which wraps a method around logger.debug, gets the file / line number, and includes that in the message?

**Comment by TheElectronWill** [comment]
It would be easier to get the line number like this rather than trying to access the jutil.Logger:
https://stackoverflow.com/questions/19610228/get-line-number-in-log-handler
