### ISSUE TITLE
LazyLogging incompatible with Serialization

### ISSUE THREAD

**Issue by pdeboer** [typesafehub/scala-logging#26]
Add @transient to lazy val in order to not break classes working with Serialization AND your logging facilities

**Comment by jeffrey-aguilera** [comment]
@lutzh Why would StrictLogger be broken? From https://www.artima.com/pins1ed/annotations.html - "Finally, Scala provides a @transient annotation for fields that should not be serialized at all. If you mark a field as @transient, then the framework should not save the field even when the surrounding object is serialized. When the object is loaded, the field will be restored to the default value for the type of the field annotated as @transient."

**Comment by orium** [comment]
#52 also fixes this.

**Comment by analytically** [comment]
Fixed in 3.2.0.
