### ISSUE TITLE
What do you think of adding logEvery(message, interval, timeunits, ..) method?

### ISSUE THREAD

**Issue by tomer-ben-david** [typesafehub/scala-logging#28]
I find in many occasions I need to re-implement some logging throttling, wouldn't it be nice to have it already existing in our logging framework?

**Comment by lutzh** [comment]
I'm not familiar with the term logging throttling. From the method signature, it seems you want to use one statement to log something periodically?
That would mean quite a change in philosophy. Now it's just a really thin layer on top of slf4j, it doesn't have any logging functionality on its own. I don't see how this would fit in there.
Also, I'm not sure that use case is really that common.
