### ISSUE TITLE
Allow Access to is<LogLevel>Enabled methods?

### ISSUE THREAD

**Issue by tarmath** [typesafehub/scala-logging#29]
Currently attempting to port my library to Scala 2.11.

I am thus moving from scalalogging to scala-logging... Whereas before I could call logger.underlying.isDebugEnabled, this is no longer possible with scala-logging.

Imagine the scenario where how much I want to log depends on the logging level:

logger.isDebugEnabled match {
  case true => logger.debug(s"STATS $stat1 $stat2 $stat3 $stat4")
  case false => logger.info(s"STATS $stat1")
}

Regardless of these methods being used behind the scene, it is still nice to access them depending on what exactly you want to do. Removing them from the exposed API removes some of the agility available to those who would employ slf4j directly for instance.

Of course, I could use multiple log lines here, but that would require quite a bit of adaptation elsewhere down our pipeline... :)

Thanks for your consideration!

**Comment by lutzh** [comment]
But there is an "underlying" field in the Logger class, https://github.com/typesafehub/scala-logging/blob/master/src/main/scala/com/typesafe/scalalogging/Logger.scala#L37

Additional evidence, this compiles and works fine:

``` 
val logger = Logger(LoggerFactory.getLogger("name"))
val sl4jLogger: org.slf4j.Logger = logger.underlying
```

Would that not solve your problem?

**Comment by tarmath** [comment]
My apologies! I managed somehow to pull in the wrong dependency definition, and that's how I ran into the issue I was having... Now I can do exactly what I had been doing before!

what I had been using for 2.10:

    compile 'com.typesafe:scalalogging-slf4j_2.10:1.0.1'

what I changed it to initially:

    compile 'com.typesafe.scala-logging:scala-logging-slf4j_2.11:2.1.2'

now (fixed):

    compile 'com.typesafe.scala-logging:scala-logging_2.11:3.1.0'

Thanks for taking time to check it out!
