### ISSUE TITLE
artifact "scala-logging" is not in Maven Central 

### ISSUE THREAD

**Issue by SillyFreak** [typesafehub/scala-logging#31]
There is one with group ID `org.helgoboss`, and an artifact with ID `scala-logging_2.11`, which I guess is what is actually meant. Fixing that in `readme.md` could avoid some confusion.

see http://search.maven.org/#search|ga|1|scala-logging

**Comment by lutzh** [comment]
sbt will add the 2.11 for you by means of the "%%", so the README.md is correct and you'll actually find the same notation in many other Scala projects.

**Comment by SillyFreak** [comment]
Ah, I was not aware of that notation, as I use Gradle and not sbt. The list above the sbt snippet, however, is just Maven artifact information, and Maven (or at least Gradle) does not infer the `_2.11`. Maybe it's just me personally, but I found that confusing.
