### ISSUE TITLE
Add OSGi manifest

### ISSUE THREAD

**Issue by FeiWongReed** [typesafehub/scala-logging#36]
Very useful library, it's really sad that it has no OSGi manifest

**Comment by nick-smith-bbp-ch** [comment]
Would it be possible to make a release with this fix included?

Many Thanks!

Nick

**Comment by FeiWongReed** [comment]
P/R link: https://github.com/typesafehub/scala-logging/pull/37

**Comment by analytically** [comment]
You closed the PR?

**Comment by FeiWongReed** [comment]
Its accepted. But looks like artifact still not released.

**Comment by nick-smith-bbp-ch** [comment]
Would it be possible to do a release?

Many thanks,

Nick
