### ISSUE TITLE
Logger.info() cannot be used with primitive types

### ISSUE THREAD

**Issue by pawel-wiejacha** [typesafehub/scala-logging#38]
Hello,

```scala
import com.typesafe.scalalogging.StrictLogging

new StrictLogging { 
  logger.info("2 + 2 == {}", new Integer(4)) // compiles
  logger.info("2 + 2 == {}", 4)              // fails to compile
}
```
The error is:
```
overloaded method value info with alternatives:
  (marker: org.slf4j.Marker,message: String,args: AnyRef*)Unit <and>
  (marker: org.slf4j.Marker,message: String)Unit <and>
  (message: String,args: AnyRef*)Unit <and>
  (message: String,cause: Throwable)Unit
cannot be applied to (String, Int)
```

Is there any reason for using `AnyRef*` instead of `Any*` in:
```scala
class Logger {
  def info(message: String, args: AnyRef*): Unit = macro LoggerMacro.infoMessageArgs
}
```

If not, I can fix it and create a PR.

**Comment by analytically** [comment]
@hseeberger I tried with Any and it seems to work fine. Might breaks binary compatibility though?

**Comment by stefanvanwouw** [comment]
I encountered the same problem and circumvented it by using Scala's String Interpolation feature http://docs.scala-lang.org/overviews/core/string-interpolation.html . When using sfl4j LoggerFactory's logger directly similar problems occur as the one you describe above.

**Comment by ilya40umov** [comment]
@stefanvanwouw String Interpolation is not an ideal solution performance-wise because the interpolation will happen before Logger checks if the message should be logged in the first place. Thus, it's quite alright to use it for error/warn levels which are unlikely to be suppressed, but for debug and info it's not an ideal solution.

Is there a PR for fixing this already? (If yes, +1 from me)

**Comment by ptxmac** [comment]
Actually the string interpolation isn't evaluated unless the logger is enabled!
The logger macros converts `logger.debug` into a if statement that checks if debug is enabled before calling the logger.

**Comment by ajozwik** [comment]
I think it is work-around for one parameter. For two the error still is here
```
 <class:line> : no `: _*' annotation allowed here
[error] (such annotations are only allowed in arguments to *-parameters)
[error]   logger.debug("{} {}", 3, 3)
```

This compile without warnings:
```scala
  logger.debug("{} {}", Int.box(3), Int.box(3))
```

**Comment by dskrvk** [comment]
Second @ajozwik. With two `Int` arguments I get the same error, but with e.g. `Int, Int, Long, Long, Long`, I get the same error as the OP (even though logger now takes `Any*`).

I don't think this issue is resolved yet.

**Comment by ptxmac** [comment]
IMHO string interpolation is a much better solution, multiple arguments feels more "Java" than Scala :smile:

**Comment by dskrvk** [comment]
I wonder if the recommendation for Scala 2.11+ users should be to prefer native interpolation to scala-logging's "{}".

**Comment by ptxmac** [comment]
Isn't string interpolation available from 2.10+ ?

**Comment by dskrvk** [comment]
You're right: http://docs.scala-lang.org/overviews/core/string-interpolation.html

All the more reasons not to use {} placeholders it seems?

**Comment by ptxmac** [comment]
I agree, but the documentation doesn't referrer to the `{}` placeholders. I think people use them if they comes from Java land and slf4j logging

**Comment by dskrvk** [comment]
Uh, indeed, the very first example in the README uses interpolation. Silly me!

**Comment by Karry** [comment]
You should not use string interpolation when you use Sentry appender (for logback). It groups log messages by its message (without arguments). When someone use string interpolation for log messages, Sentry grouping stops work!

**Comment by mentegy** [comment]
Hello, checkout https://scastie.scala-lang.org/3GLKMBwvQbq1N54BfkjlBA
this seems not to be fixed

**Comment by ptxmac** [comment]
> You should not use string interpolation when you use Sentry appender (for logback). It groups log messages by its message (without arguments). When someone use string interpolation for log messages, Sentry grouping stops work!

That's a good point! I wonder if it would be possible to do some macro magic on the interpolated strings and split them in groups
