### ISSUE TITLE
scala 2.12 build on maven central

### ISSUE THREAD

**Issue by fabiofumarola** [typesafehub/scala-logging#61]
is there a build published for scala 2.12?

**Comment by gheine** [comment]
+1

**Comment by Gospodzin** [comment]
+1 This is the only library that stops me from migrating to 2.12

**Comment by SethTisue** [comment]
@analytically any possibility of getting this published for 2.12.0-RC1?

**Comment by magicknot** [comment]
Any news on this?

**Comment by analytically** [comment]
I'm working on it, just pushed a new build that cross publishes when releasing. I'll test the build a bit more (especially osgi) and release this weekend.

**Comment by analytically** [comment]
Published, should be available within 24h.

**Comment by SethTisue** [comment]
awesome! I added it over at https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md

**Comment by analytically** [comment]
Thanks (you forgot a " on that page)!

**Comment by SethTisue** [comment]
fixed

**Comment by magicknot** [comment]
A new version of Scala 2.12 is out (2.12.0-RC2). Can you publish a build for it?

**Comment by analytically** [comment]
Once scalatest is released for 2.12.0-RC2 I'll release scala-logging as well.

**Comment by gslowikowski** [comment]
ScalaTest released today.

**Comment by analytically** [comment]
I've published 3.5.0 for 2.12.0-RC2.
