### ISSUE TITLE
Disable logging at runtime

### ISSUE THREAD

**Issue by jarandaf** [typesafehub/scala-logging#63]
I would like to disable logging in some of my tests. What is the recommended way to achieve it? I am trying the following but logs are still present (please notice I am using `Logback` as logging backend):

```scala
import ch.qos.logback.classic.{Logger, Level}
import org.slf4j.LoggerFactory

val rootLogger = LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME).asInstanceOf[Logger]
rootLogger.setLevel(Level.OFF)
```

All my classes basically extend `LazyLogging` trait.

**Comment by analytically** [comment]
Use LogBack's level for this.
