### ISSUE TITLE
Why macros?

### ISSUE THREAD

**Issue by dylanwilder** [typesafehub/scala-logging#73]
in my experimenting the following yields the same result without the need for macros:
```scala
def debug(msg: => String) = if (loglevel >= Debug) println(msg) else ()
```
thus you can uses scalas built in string interpolation
```scala
logger.debug(s"Output is: ${expensiveFunc()}")
```

**Comment by notxcain** [comment]
@dylanwilder I think the problem with call-by-name params is that it creates a `Function0` instance for each call, which is effectively this `logger.debug(() => s"Output is: ${expensiveFunc()}")`. So this is kinda expensive.
