### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings.

### ISSUE THREAD

**Issue by jiakechong1991** [typesafehub/scala-logging#81]
I see the page,this write
`libraryDependencies += "com.typesafe.scala-logging" % "scala-logging_2.11" % "3.1.0"

libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.1.2"
`
but I get
`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/wangxiaoke/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/wangxiaoke/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
`
if I write
`libraryDependencies += "com.typesafe.scala-logging" % "scala-logging_2.11" % "3.1.0"
`
I will ok! so I think the author is wrong at README?

**Comment by analytically** [comment]
Nowhere is slf4j-log4j12 mentioned in the README.
