### ISSUE TITLE
macros should fully qualify all external-referencing identifiers

### ISSUE THREAD

**Issue by retronym** [typesafehub/scala-logging#82]
e.g. `List` [here](https://github.com/typesafehub/scala-logging/blob/1e289c62fa3d962d2cf72ded49cfc09dbad09f69/src/main/scala/com/typesafe/scalalogging/LoggerMacro.scala#L44), should be `_root_.scala.List`.

I spotted 9 other occurrences of this problem in that file.

**Comment by analytically** [comment]
Fixed, thanks!
