### ISSUE TITLE
LazyLogger should be marked @transient

### ISSUE THREAD

**Issue by hindog** [typesafehub/scala-logging#84]
Serialization is broken for any class that implements `LazyLogging` after the logger has been initialized.  This could be remedied by marking the field as `@transient`, forcing the logger to re-initialize on deserialization

**Comment by analytically** [comment]
From the Slf4J docs:

"Contrary to static variables, instance variables are serialized by default. As of SLF4J version 1.5.3, logger instances survive serialization. Thus, serialization of the host class no longer requires any special action, even when loggers are declared as instance variables. In previous versions, logger instances needed to be declared as transient in the host class."
