### ISSUE TITLE
Publish 3.7.2 version for Scala 2.13.0-M1

### ISSUE THREAD

**Issue by gslowikowski** [typesafehub/scala-logging#93]
Scoverage library depends on `scala-logging` and cannot publish a version for Scala `2.13.x` without `scala-logging` for this version being available first.

**Comment by povder** [comment]
See PR https://github.com/typesafehub/scala-logging/pull/94

**Comment by SethTisue** [comment]
I see that #94 was merged; has the publishing part happened...?

**Comment by analytically** [comment]
I've just published scala-logging_2.13.0-M1-3.7.2.jar.

**Comment by analytically** [comment]
Ha - `org.scalatest#scalatest_2.13.0-M2;3.0.3: not found`
